name: Valhalla Ubuntu Build
on: [push]

jobs:
  build:
    name: Ubuntu build
    runs-on: ubuntu-latest
    steps:
      - name: Get dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            curl libcurl4 libcurl4-gnutls-dev \
            mlocate \
            libboost-all-dev \
            libluajit-5.1-dev \
            protobuf-compiler \
            libgeos++-dev \
            libprotobuf-dev \
            protobuf-compiler
          apt list --installed | grep curl  
          sudo updatedb
          locate libcurl.so
          locate curl.h
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Configure and run build
        run: |
          mkdir build && cd build \
          && cmake .. \
            -DCMAKE_CROSS_COMPILING=1 \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_TOOLS=OFF \
            -DENABLE_DATA_TOOLS=OFF \
            -DENABLE_SERVICES=OFF \
            -DENABLE_PYTHON_BINDINGS=ON \
            -DENABLE_CCACHE=OFF \
            -DENABLE_TESTS=OFF \
            -DENABLE_BENCHMARKS=OFF \
            -DLOGGING_LEVEL=DEBUG \
            -DBoost_PROGRAM_OPTIONS_LIBRARY=/usr/x86_64-w64-mingw32/sys-root/mingw/lib/libboost_program_options-mt-x64.dll.a \
            -DPYTHON_EXECUTABLE=/usr/x86_64-w64-mingw32/bin/python3 \
            -DPYTHON_LIBRARIES=/usr/x86_64-w64-mingw32/sys-root/mingw/lib/libpython3.9.dll.a \
            -DPYTHON_INCLUDE_DIRS=/usr/x86_64-w64-mingw32/sys-root/mingw/include/python3.9 \
          && make -j$(nproc)
