name: Valhalla Ubuntu Build
on: [push]

jobs:
  build:
    name: Ubuntu build
    runs-on: ${{ matrix.os }}

    strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest]
          tools: [OFF]
          datatools: [ON]
          # services ON needs libprime_server
          services: [OFF]
          ccache: [OFF]
          tests: [OFF]
          benchmarks: [OFF]


    steps:
      - uses: actions/checkout@v2
      - name: Cache submodules
        id: cache-third_party
        uses: actions/cache@v3
        with:
          path: third_party
          key: ${{ runner.os }}-third_party

      - name: Checkout submodules
        if: steps.cache-third_party.outputs.cache-hit != 'true'
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

      - name: Get dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            curl libcurl4 libcurl4-gnutls-dev \
            libboost-all-dev \
            libprotobuf-dev \
            protobuf-compiler
          #libluajit-5.1-dev \
          #mlocate \
          #apt list --installed | grep curl  
          #sudo updatedb
          #locate libcurl.so
          #locate curl.h

      - name: get datatools dependencies
        if: ${{ matrix.datatools  == 'ON' }}
        run: |
          sudo apt-get install -y \
            libspatialite-dev \
            libluajit-5.1-dev \
            libgeos++-dev

      - name: Configure
        run: |
          mkdir build && cd build \
          && cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_TOOLS=${{ matrix.tools }} \
            -DENABLE_DATA_TOOLS=${{ matrix.datatools }} \
            -DENABLE_SERVICES=${{ matrix.services }} \
            -DENABLE_CCACHE=${{ matrix.ccache }} \
            -DENABLE_TESTS=${{ matrix.tests }} \
            -DENABLE_BENCHMARKS=${{ matrix.benchmarks }}
      - name: build
        run: |
          cd build \
          && make -j$(nproc)
