name: Valhalla Ubuntu Build
on: [push]

jobs:
  build:
    name: Ubuntu build
    runs-on: ${{ matrix.os }}

    strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, ubuntu-20.04]
          tools: [ON, OFF]
          datatools: [ON, OFF]
          services: [ON, OFF]
          ccache: [ON, OFF]
          tests: [ON, OFF]

    steps:
      - name: Get dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            curl libcurl4 libcurl4-gnutls-dev \
            mlocate \
            libboost-all-dev \
            libluajit-5.1-dev \
            protobuf-compiler \
            libgeos++-dev \
            libprotobuf-dev \
            protobuf-compiler
          #apt list --installed | grep curl  
          #sudo updatedb
          #locate libcurl.so
          #locate curl.h
      - uses: actions/checkout@v2
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Configure
        run: |
          mkdir build && cd build \
          && cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_TOOLS=${{ matrix.tools }} \
            -DENABLE_DATA_TOOLS=${{ matrix.datatools }} \
            -DENABLE_SERVICES=${{ matrix.services }} \
            -DENABLE_CCACHE=${{ matrix.ccache }} \
            -DENABLE_TESTS=${{ matrix.tests }} \
      - name: run build
        run: |
          cd build \
          && make -j$(nproc)
      - name: tests

